// Builds src/data/cards.js from data/genesis.csv + data/mainframes.json.
// No dependencies. Run: node scripts/build-data.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

export function parseCsv(text) {
  if (text.charCodeAt(0) === 0xfeff) text = text.slice(1);
  const rows = [];
  let row = [], field = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') q = false;
      else field += c;
    } else if (c === '"') q = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++;
      row.push(field); field = '';
      if (row.some((v) => v !== '')) rows.push(row);
      row = [];
    } else field += c;
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const list = (s) => s.split(',').map((x) => x.trim()).filter(Boolean);
const num = (s) => (s === '' ? null : Number(s));

// data/abilities_raw.txt: id|ability name|RAM cost|run icon. Names ending "(name cut off)" were truncated on the card image.
export function parseAbilities(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    if (!line.trim() || line.startsWith('#')) continue;
    const [id, rawName, ram, run] = line.split('|');
    const cut = /\(name cut off\)/.test(rawName);
    const name = rawName.replace(/\s*\(name cut off\)/, '').trim() + (cut ? '…' : '');
    (out[id] ||= []).push({ name, ram: ram === '' ? null : Number(ram), run: run === '1' });
  }
  return out;
}

export function buildCards(csvText, mainframes, abilities = {}) {
  const [head, ...rows] = parseCsv(csvText);
  const ix = Object.fromEntries(head.map((h, i) => [h, i]));
  const cards = rows.map((r) => {
    const g = (h) => r[ix[h]] ?? '';
    const id = Number(g('ID'));
    const card = {
      id,
      name: g('Name'),
      type: g('Type'),
      subtype: g('Subtype'),
      factions: [g('Faction 1'), g('Faction 2')].filter(Boolean),
      tags: list(g('Tags')),
      frame: g('Frame'),
      ram: num(g('RAM Cost')),
      atk: num(g('ATK')),
      def: num(g('DEF')),
      rarity: g('Rarity'),
      copyLimit: Number(g('Copy Limit')),
      iconic: g('Iconic') === 'Yes',
      keywords: list(g('Keywords Mentioned')),
      refs: list(g('References (factions / tags / cards)')),
      dmg: g('Damage Type Referenced'),
      text: g('Rules Text').split(' // ').filter(Boolean),
    };
    if (abilities[String(id)]) card.abilities = abilities[String(id)];
    const mf = mainframes[String(id)];
    if (mf) card.mainframe = { lead: mf.lead, tiers: mf.tiers };
    return card;
  });
  cards.sort((a, b) => a.id - b.id);
  return cards;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const csv = readFileSync(join(root, 'data/genesis.csv'), 'utf8');
  const mf = JSON.parse(readFileSync(join(root, 'data/mainframes.json'), 'utf8'));
  const ab = parseAbilities(readFileSync(join(root, 'data/abilities_raw.txt'), 'utf8'));
  const cards = buildCards(csv, mf, ab);
  mkdirSync(join(root, 'src/data'), { recursive: true });
  writeFileSync(join(root, 'src/data/cards.js'), '// Generated by scripts/build-data.mjs from data/. Do not edit by hand.\nexport const cards = ' + JSON.stringify(cards) + ';\n');
  const mains = cards.filter((c) => c.mainframe).length;
  console.log(`cards: ${cards.length}, mainframes with tiers: ${mains}, cards with costed abilities: ${cards.filter((c) => c.abilities).length}`);
}
